# Generated by Django 4.2.26 on 2025-12-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0001_initial'),
        ('users', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_resources',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='library.resource'),
        ),
    ]
